Gal 184/deploy UI build pipeline
NHSDigital/Galleri-Frontend pull request #1
Opened 2023-07-12 13:50 UTC by msandhuNHS

Deploying next app via build pipeline into aws.

## Description

## Context

## Type of changes

- [ ] Refactoring (non-breaking change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
- [ ] I have followed the code style of the project
- [ ] I have added tests to cover my changes
- [ ] I have updated the documentation accordingly
- [ ] This PR is a result of pair or mob programming

---

## Sensitive Information Declaration

To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this matter.

- [ ] I confirm that neither PII/PID nor sensitive data are included in this PR and the codebase changes.

2023-07-12 16:06 UTC, zainm97 requested changes
Left some comment that need to be closed out. Nothing major but looks like good work so far

2023-07-12 16:06 UTC, zainm97 commented on .github/workflows/deploy.yaml
> +  AWS_REGION : "eu-north-1"
can we add this as a env variable

2023-07-12 16:06 UTC, zainm97 commented on .github/workflows/deploy.yaml
> +  BUCKET_NAME : "arn:aws:s3:::gps-client"
and this potentially? Might have to wait for the terraform ticket to be created and take the bucket name from there but for time being we can create repo env variable?

2023-07-12 16:06 UTC, zainm97 commented on .github/workflows/deploy.yaml
> +name: Deploy app to AWS
consider renaming the yaml to something more specific. Deploy is generic

2023-07-12 16:06 UTC, zainm97 commented on .github/workflows/cicd-pipeline.yaml
> +    uses: ./.github/workflows/deploy.yaml
see below comment

2023-07-12 16:06 UTC, zainm97 commented on .github/workflows/deploy.yaml
> +          role-to-assume: arn:aws:iam::136293001324:role/github-oidc-role
env variable

2023-07-12 16:06 UTC, zainm97 commented on .github/workflows/deploy.yaml
> +          role-session-name: githubRoleSession
env variable

2023-07-12 16:06 UTC, zainm97 commented on .github/workflows/deploy.yaml
> +          aws s3 sync ./out s3://gps-client/
s3 bucket name to be env variable or secret. Need to remember that this is a public repo

2023-07-12 16:06 UTC, zainm97 commented on .gitignore
> +/node_modules
Noice

2023-07-12 16:06 UTC, zainm97 commented on Makefile
> -		asdf-install \
instead of removing need to keep this in and just comment out. Need to message Dan Stefaniuk `make config` command not working when asdf-install is present so he can put in a patch

2023-07-12 16:06 UTC, zainm97 commented on README.md
> +Make use of this repository template to expedite your project setup and enhance your productivity right from the get-go. Enjoy the advantage of having a well-structured, self-documented project that
remove

2023-07-12 16:06 UTC, zainm97 commented on next.config.js
> +/** @type {import('next').NextConfig} */
looks like comment that is left in

2023-07-13 10:57 UTC, msandhuNHS commented on .github/workflows/deploy.yaml
> +          aws s3 sync ./out s3://gps-client/
Can't access s3 bucket with name as it's private, only visible via cloud front

2023-07-14 13:12 UTC, msandhuNHS commented
replicate branch not needed

2023-07-14 13:12 UTC, closed without merging