Feature/cypresss
NHSDigital/Galleri-Frontend pull request #106
Opened 2024-01-16 13:53 UTC by SwetaPatel1

## Description cypressTests

## Context 

## Type of changes

- [ ] Refactoring (non-breaking change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
- [x] I have followed the code style of the project
- [x] I have added tests to cover my changes
- [ ] I have updated the documentation accordingly
- [ ] This PR is a result of pair or mob programming

---

## Sensitive Information Declaration

To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this matter.

- [x] I confirm that neither PII/PID nor sensitive data are included in this PR and the codebase changes.

2024-01-16 17:20 UTC, zainm97 requested changes
Tests are hard to read as there is no indentation. 

API IDs have been hard coded and the testing should not point to dev environment. 

Please format correctly and submit using the appropiate environment variables to allow for reviewers to read code easier

2024-03-07 09:57 UTC, andrew-cleveland commented on src/app/page.jsx
> +  const roles = ["Invitation Planner", "Referring Nurse"];
should the role not be "Referring Clinician"?

2024-03-07 10:00 UTC, andrew-cleveland commented on src/app/views/clinic_information/ClinicInformation.js
> +        `https://qlyc7rlmp6.execute-api.eu-west-2.amazonaws.com/uat-1/put-target-percentage`,
The ID will change regularly, I would suggest storing this as an environmental variable which can be read in. Otherwise this will need to be updated very frequently.

2024-03-07 10:00 UTC, andrew-cleveland commented on src/app/views/clinic_information/ClinicInformation.js
> +        `https://riit28f4fl.execute-api.eu-west-2.amazonaws.com/uat-1/calculate-num-to-invite`,
the ID value should be a variable

2024-03-07 10:00 UTC, andrew-cleveland commented on src/app/views/clinic_information/ClinicInformation.js
> +      `https://uhclz23uaj.execute-api.eu-west-2.amazonaws.com/uat-1/clinic-information?clinicId=${clinicId}&clinicName=${clinicName}`
the ID value should be a variable

2024-03-07 10:01 UTC, andrew-cleveland commented on src/app/views/clinic_information/ClinicInformation.js
> +          `https://uhclz23uaj.execute-api.eu-west-2.amazonaws.com/uat-1/clinic-information?clinicId=${currentlySelectedClinicId}&clinicName=${currentlySelectedClinic}`
These values should stay as environment variables

2024-03-07 10:02 UTC, andrew-cleveland commented on src/app/views/clinic_information/ClinicInformation.js
> +        `https://e7c24dsi1f.execute-api.eu-west-2.amazonaws.com/uat-1/clinic-icb-list?participatingIcb=${this.context.state.icbSelected}`
These values should stay as environment variables

2024-03-07 10:03 UTC, andrew-cleveland commented on src/app/views/clinic_information/ClinicInformation.js
> +            `https://uhclz23uaj.execute-api.eu-west-2.amazonaws.com/uat-1/clinic-information?clinicId=${initialSelectedClinicId}&clinicName=${initialSelectedClinic}`
These values should stay as environment variables

2024-03-07 10:03 UTC, andrew-cleveland commented on src/app/views/clinic_information/ClinicInformation.js
> +<<<<<<< HEAD
This is a merge conflict that needs to be resolved

2024-03-07 10:03 UTC, andrew-cleveland commented on src/app/views/clinic_information/ClinicInformation.js
> +          `https://9wgcg7ed18.execute-api.eu-west-2.amazonaws.com/uat-1/get-lsoa-in-range?clinicPostcode=${this.context.state.postcode}&miles=${this.state.rangeSelection}`
These values should stay as environment variables

2024-03-07 10:04 UTC, andrew-cleveland commented on src/app/views/clinic_summary/ClinicSummary.js
> +        `https://iajb6ya6ed.execute-api.eu-west-2.amazonaws.com/dev/participating-icb-list`
These values should stay as environment variables

2024-03-07 10:05 UTC, andrew-cleveland commented on src/app/views/invitation_planning/InvitationPlanning.js
> +        `https://1295kemqce.execute-api.eu-west-2.amazonaws.com/dev/invitation-parameters-put-forecast-uptake`,
These values should stay as environment variables

2024-03-07 10:05 UTC, andrew-cleveland commented on src/app/views/invitation_planning/InvitationPlanning.js
> +        `https://3pp8n817jj.execute-api.eu-west-2.amazonaws.com/dev/invitation-parameters-put-quintiles`,
These values should stay as environment variables

2024-03-07 10:05 UTC, andrew-cleveland commented on src/app/views/invitation_planning/InvitationPlanning.js
> +        `https://31qaemtf43.execute-api.eu-west-2.amazonaws.com/dev/invitation-parameters`
These values should stay as environment variables

2024-03-07 10:05 UTC, andrew-cleveland commented on src/app/views/invitation_summary/InvitationSummary.js
> +      `https://7aclx0b1e0.execute-api.eu-west-2.amazonaws.com/dev/clinic-information?clinicId=${clinicId}&clinicName=${clinicName}`
These values should stay as environment variables

2024-03-07 10:05 UTC, andrew-cleveland commented on src/app/views/invitation_summary/InvitationSummary.js
> +      `https://o41rwmyvv7.execute-api.eu-west-2.amazonaws.com/dev/generate-invites`,
These values should stay as environment variables

2024-03-07 10:07 UTC, andrew-cleveland commented on cypress/e2e/DataDrivenTesting/data_driven_tests.cy.js
> +cy.get('*[id="Phlebotomy clinic 61"]')
The valid clinics can change across environments so this may be better off as a variable which can be updated easily.

2024-03-07 10:08 UTC, andrew-cleveland commented on cypress/e2e/DataDrivenTesting/data_driven_tests.cy.js
> +.select('Phlebotomy clinic 5')
The valid clinics can change across environments so this may be better off as a variable which can be updated easily.

2024-03-07 10:08 UTC, andrew-cleveland commented on cypress/e2e/DataDrivenTesting/data_driven_tests.cy.js
> +cy.get('*[id="Phlebotomy clinic 23"]')
The valid clinics can change across environments so this may be better off as a variable which can be updated easily.

2024-03-07 10:09 UTC, andrew-cleveland commented on cypress/e2e/DataDrivenTesting/data_driven_tests.cy.js
> +cy.get('*[id="Phlebotomy clinic 55"]')
The valid clinics can change across environments so this may be better off as a variable which can be updated easily.

2024-03-07 10:09 UTC, andrew-cleveland commented on cypress/e2e/DataDrivenTesting/data_driven_tests.cy.js
> +.select('Phlebotomy clinic 40')
The valid clinics can change across environments so this may be better off as a variable which can be updated easily.

2024-03-07 10:09 UTC, andrew-cleveland commented on cypress/e2e/DataDrivenTesting/data_driven_tests.cy.js
> +cy.get('*[id="Phlebotomy clinic 20"]')
The valid clinics can change across environments so this may be better off as a variable which can be updated easily.

2024-03-07 10:10 UTC, andrew-cleveland commented on cypress/e2e/DataDrivenTesting/data_driven_tests.cy.js
> +cy.get('*[id="Phlebotomy clinic 44"]')
The valid clinics can change across environments so this may be better off as a variable which can be updated easily.

2024-03-07 10:11 UTC, andrew-cleveland commented on cypress/e2e/DataDrivenTesting/data_driven_tests.cy.js
> +cy.visit("http://uat-2-invitations-frontend.eba-mas6i84b.eu-west-2.elasticbeanstalk.com/")
This address should be a variable which can be adjusted to target different environments

2024-03-07 10:11 UTC, andrew-cleveland commented on cypress/e2e/First Automation Regression Tests/first_automation_tests.cy.js
> +cy.visit("http://uat-2-invitations-frontend.eba-mas6i84b.eu-west-2.elasticbeanstalk.com/")
This address should be a variable which can be adjusted to target different environments

2024-03-07 10:15 UTC, andrew-cleveland commented on src/app/views/clinic_information/ClinicInformation.js
> +<<<<<<< HEAD
This is a merge conflict that needs to be resolved

2024-04-05 15:42 UTC, avi312NHS commented
Hey @SwetaPatel1 does this PR still need to be open or can we close it for now?

2024-04-05 16:01 UTC, avi312NHS commented
Closing for now, @SwetaPatel1 reopen when you are ready! 😄

2024-04-05 16:01 UTC, closed without merging