Gal 202/invitation clinic summary
NHSDigital/Galleri-Frontend pull request #12
Opened 2023-08-18 11:26 UTC by msandhuNHS

## Description

Added Clinic Summary page.

## Context

## Type of changes

- [ ] Refactoring (non-breaking change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
- [ ] I have followed the code style of the project
- [ ] I have added tests to cover my changes
- [ ] I have updated the documentation accordingly
- [ ] This PR is a result of pair or mob programming

---

## Sensitive Information Declaration

To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this matter.

- [ ] I confirm that neither PII/PID nor sensitive data are included in this PR and the codebase changes.

2023-08-18 11:35 UTC, joad432 submitted a review, later dismissed
Nice thank you.

2023-08-23 10:56 UTC, LaithM96 reviewed
Can you please review my comments and then I will approve once I am satisfied with the comments :)

2023-08-23 10:56 UTC, LaithM96 commented on package.json
>      "react": "18.2.0",
Decide on a versioning strategy. If you want to pin versions, do it for all packages. If you want to use semantic versioning, use it consistently.

2023-08-23 10:56 UTC, LaithM96 commented on package-lock.json
> -{
why was this file deleted ?

2023-08-23 10:56 UTC, LaithM96 commented on gulpfile.js
> +
Sass Compilation - Make sure to document how and when to run this task, especially if it's not integrated into your build process. Possible run book ?

2023-08-23 10:56 UTC, LaithM96 commented on .gitignore
> +
Good practice to ignore these directories. Continue doing this.

2023-08-23 10:56 UTC, LaithM96 commented on next.config.js
> +const nextConfig = {};
Webpack Config: Ensure that the custom Webpack configuration is well-documented.

2023-08-23 10:56 UTC, LaithM96 commented on .editorconfig
> +[{Makefile,*.mk,go.mod,go.sum,*.go,.gitmodules,*.scss,*.css}]
- Non-root User: Good practice, continue doing this.
- Environment Variables: Make sure these are documented for anyone using the Dockerfile.

2023-08-23 10:56 UTC, LaithM96 commented on package.json
>      "node_modules/",
The "cacheDirectories" key is not standard for a package.json file. ??

2023-08-23 11:14 UTC, LaithM96 approved these changes
happy to approve, well done, after the demo for this front end work.

2023-08-23 11:18 UTC, LaithM96 requested changes
dev 3 needs to be merged into main first.

2023-08-30 15:53 UTC, zainm97 approved these changes

2023-08-30 15:53 UTC, zainm97 commented on .gitignore
> +/package-lock.json
done

2023-08-30 15:55 UTC, LaithM96 approved these changes
approved, all good :)

2023-08-30 15:56 UTC, merged