Gal 320/integrate cypress for testing
NHSDigital/Galleri-Frontend pull request #20
Opened 2023-09-01 09:18 UTC by LaithM96

## Description

Added cypress config files and folder to make it easier to run our tests in the other repos and use this as a base.

## Context

To make it easier for testers to run tests and don't need to organise testing folders everytime.

## Type of changes

- [ ] Refactoring (non-breaking change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
- [ ] I have followed the code style of the project
- [ ] I have added tests to cover my changes
- [ ] I have updated the documentation accordingly
- [ ] This PR is a result of pair or mob programming

---

## Sensitive Information Declaration

To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this matter.

- [ ] I confirm that neither PII/PID nor sensitive data are included in this PR and the codebase changes.

2023-09-01 09:45 UTC, joad432 approved these changes
The folder structures look good, everything looks set up correctly. Nice!!!

2023-09-03 14:58 UTC, zainm97 requested changes
This needs rebasing on the top of the develop 4. Also need to remove boilerplate code that is not relevant to out project

2023-09-03 14:58 UTC, zainm97 commented on .editorconfig
> +[{Makefile,*.mk,go.mod,go.sum,*.go,.gitmodules,*.scss,*.css}]
why has css and scss been added to the editor config?

2023-09-03 14:58 UTC, zainm97 commented on Makefile
> +		asdf-install \
why has asdf-install been included back in

2023-09-03 14:58 UTC, zainm97 commented on cypress/support/e2e.js
> +// Alternatively you can use CommonJS syntax:
remove commonJS

2023-09-05 10:28 UTC, joad432 commented on cypress/readme
Line 3: our e2e tests will be stored in the 'cypress/e2e' folder not 'cypress/integration/e2e'. It's important that we have consistency.

2023-09-05 10:32 UTC, joad432 commented on cypress/readme
With my previous comment, it is the same same thing with Line 5, 7, 9, 11. Need to ensure that we have the correct paths noted in the readme file and it is kept consistent throughout.

2023-09-05 10:34 UTC, joad432 commented on package.json
> -    "test": "jest --watch"
There is a duplicate line below, is that how it's supposed to be?

2023-09-05 10:35 UTC, joad432 commented on package.json
> -    "sass": "^1.64.2"
Another duplicate for line of code.

2023-09-05 10:38 UTC, joad432 requested changes
I've added my comments and everything looks good, just need a few changes here and there which I've commented in their respective areas.

2023-09-06 14:15 UTC, zainm97 commented on package.json
> -    "test": "jest --watch"
this is fine, theres just an additional comma added

2023-09-06 14:15 UTC, zainm97 commented on package.json
> -    "sass": "^1.64.2"
this is fine, theres just an additional comma added

2023-09-06 14:17 UTC, zainm97 submitted a review, later dismissed
pls add the folders but looks good

2023-09-06 14:17 UTC, zainm97 commented on cypress.config.cjs
> +  screenshotsFolder: 'cypress/screenshots',
make sure these folders exist

2023-09-06 14:17 UTC, zainm97 commented on cypress.config.cjs
> +  videosFolder: 'cypress/videos',
and this

2023-09-06 15:08 UTC, LaithM96 commented on cypress.config.cjs
> +  screenshotsFolder: 'cypress/screenshots',
they do :)

2023-09-06 15:08 UTC, LaithM96 commented on cypress.config.cjs
> +  videosFolder: 'cypress/videos',
and this one exist too

2023-09-06 16:02 UTC, msandhuNHS commented on cypress/e2e/accessibility/accessibility.spec.cy.js
> +    cy.get('#select-icb').select('Participating ICB 4');
Looks good but you'll need to edit this to match the real data when we have it.

2023-09-06 16:02 UTC, msandhuNHS submitted a review, later dismissed

2023-09-06 19:46 UTC, joad432 approved these changes
Nice!!

2023-09-07 08:23 UTC, joad432 commented on cypress/readme
Still need to change all paths to cypress/e2e/whatever else is needed here. The paths aren't cypress/integration/accessibility or cypress/integration/api, etc., they need to be cypress/e2e/accessibility or cypress/e2e/api. 

We need to make sure we have the right paths to avoid confusion especially if new colleagues arrive

2023-09-07 08:46 UTC, joad432 approved these changes
Nice everything looks good now

2023-09-07 09:27 UTC, zainm97 approved these changes
good

2023-09-07 09:28 UTC, merged