Gal 296/invitations screen clinic information
NHSDigital/Galleri-Frontend pull request #25
Opened 2023-09-12 15:24 UTC by msandhuNHS

## Description
https://nhsd-jira.digital.nhs.uk/browse/GAL-296

As we do not have a custom domain, the API id for the fetch calls will change on each build of the backend thus must be updated accordingly. 

Clinic Information screens implemented.

## Context

## Type of changes

- [ ] Refactoring (non-breaking change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
- [ ] I have followed the code style of the project
- [ ] I have added tests to cover my changes
- [ ] I have updated the documentation accordingly
- [ ] This PR is a result of pair or mob programming

---

## Sensitive Information Declaration

To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this matter.

- [ ] I confirm that neither PII/PID nor sensitive data are included in this PR and the codebase changes.

2023-09-12 16:21 UTC, joad432 approved these changes
Good good!!

2023-09-12 16:54 UTC, LaithM96 requested changes
[Invalid workflow file: .github/workflows/deploy-to-s3.yaml#L17](https://github.com/NHSDigital/Galleri-Frontend/actions/runs/6161665835/workflow)
You have an error in your yaml syntax on line 17

2023-09-13 09:26 UTC, LaithM96 approved these changes
I spoke to Manny and this file is not been used just yet, and it shouldn’t have any problem with it.

2023-09-18 11:26 UTC, joad432 commented on package.json
> -    "cypress": "^12.17.4",
This being removed, will this affect myself and Laith when it comes to testing? Will we have to install Cypress again?

2023-09-18 11:45 UTC, joad432 requested changes
pleasee check comment on package.json

2023-09-18 13:09 UTC, joad432 submitted a review, later dismissed
Looks good

2023-09-20 14:48 UTC, zainm97 approved these changes

2023-09-20 14:52 UTC, joad432 approved these changes

2023-09-20 14:53 UTC, merged