Gal 316/target percentage
NHSDigital/Galleri-Frontend pull request #35
Opened 2023-10-23 15:33 UTC by Amar-NHS

## Description

https://nhsd-jira.digital.nhs.uk/browse/GAL-316

Created the "Clinic Invitation Criteria" Section within the Clinic Invitation Page. Implemented the functionality - API calls and integrated it within the button.

## Context

## Type of changes

- [x ] Refactoring (non-breaking change)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
- [ ] I have followed the code style of the project
- [ ] I have added tests to cover my changes
- [ ] I have updated the documentation accordingly
- [ ] This PR is a result of pair or mob programming

---

## Sensitive Information Declaration

To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this matter.

- [ ] I confirm that neither PII/PID nor sensitive data are included in this PR and the codebase changes.

2023-10-24 11:31 UTC, zainm97 commented on src/app/views/clinic_information/ClinicInformation.js
> +      "isInputTargetPercentageExceed" : true,
should this default to false? Don't think it matters either way but makes more sense imo

2023-10-24 11:31 UTC, zainm97 commented on src/app/views/clinic_information/ClinicInformation.js
> +      "isInputTargetPercentageTotal" : true,
name of this variable is a tad confusion as to what its trying to represent

2023-10-24 11:32 UTC, zainm97 commented on src/app/views/clinic_information/ClinicInformation.js
> +      "inputValue" : 0,
targetFillToInputValue makes it more clear

2023-10-24 11:32 UTC, zainm97 commented on src/app/views/clinic_information/ClinicInformation.js
> +    this.onClickUpdateHandler = this.onClickUpdateHandler.bind(this);
make variable more clear

2023-10-24 11:32 UTC, zainm97 commented on src/app/views/clinic_information/ClinicInformation.js
> +    this.handleInputChange = this.handleInputChange.bind(this);
make variable more clear

2023-10-24 11:33 UTC, zainm97 commented on src/app/views/clinic_information/ClinicInformation.js
> +    const {recentInvitationHistory} = this.state;
can just directly call this in line 52 -> this.state.recentInvitationHistory.appsRemaining....

2023-10-24 11:35 UTC, zainm97 commented on src/app/views/clinic_information/ClinicInformation.js
> +      return response.data; // You might want to return the response data too.
remove comment

2023-10-24 11:36 UTC, zainm97 commented on src/app/views/clinic_information/ClinicInformation.js
> +      console.log("Response status: " + response.status);
do we need

2023-10-24 11:37 UTC, zainm97 commented on src/app/views/clinic_information/ClinicInformation.js
> +      throw error; // Re-throw the error to propagate it.
think can remove line 73. Line 72 will throw an error using the console.error

2023-10-24 11:44 UTC, zainm97 commented on src/app/views/clinic_information/ClinicInformation.js
> +    if (!value) {
can do if(!value || value > 100) to squash the second if statement from line 90 and 98

2023-10-24 11:49 UTC, zainm97 commented on src/app/views/clinic_information/ClinicInformation.js
> +        console.log(response);
remove

2023-10-24 11:49 UTC, zainm97 commented on src/app/views/clinic_information/ClinicInformation.js
> +        console.log(targetPercentageValue);
remove

2023-10-24 11:56 UTC, zainm97 commented on src/app/views/clinic_information/ClinicInformationPage.jsx
> +          {/* // add your invitation criteria component here */}
remove

2023-10-24 11:57 UTC, zainm97 commented on src/app/views/clinic_information/clinic_invitation_criteria/ClinicInvitationCriteria.jsx
> +  // const { appsRemaining } =
remove

2023-10-24 11:57 UTC, zainm97 commented on src/app/views/clinic_information/clinic_invitation_criteria/ClinicInvitationCriteria.jsx
> +      <h2 label="header">Clinic Invitation Criteria</h2>
add id field

2023-10-24 11:58 UTC, zainm97 commented on src/app/views/clinic_information/clinic_invitation_criteria/ClinicInvitationCriteria.jsx
> +      <br />
wanna reduce the need for br cos i think they cause ac11y issues

2023-10-24 11:58 UTC, zainm97 commented on src/app/views/clinic_information/clinic_invitation_criteria/ClinicInvitationCriteria.jsx
in general add id to the elements on this page

2023-10-24 11:59 UTC, zainm97 commented on src/app/views/clinic_information/clinic_invitation_criteria/ClinicInvitationCriteria.jsx
> +            name="weight"
what does weight represent?

2023-10-24 11:59 UTC, zainm97 commented on src/app/views/clinic_information/clinic_invitation_criteria/ClinicInvitationCriteria.jsx
> +            data-testid="input-target-percentage"
think we use id instead of data-testid

2023-10-24 12:02 UTC, zainm97 requested changes
please see comments

2023-10-24 14:50 UTC, Amar-NHS commented on src/app/views/clinic_information/ClinicInformation.js
> +      "isInputTargetPercentageTotal" : true,
We replaced both of them with - "hideUserErrorTargetPercentageTotal" & "hideUserErrorTargetPercentageExceed".

2023-10-24 14:59 UTC, Amar-NHS commented on src/app/views/clinic_information/ClinicInformation.js
> +    this.onClickUpdateHandler = this.onClickUpdateHandler.bind(this);
replaced it to "onClickTargetAppsToFillHandler" for clarity

2023-10-24 14:59 UTC, Amar-NHS commented on src/app/views/clinic_information/ClinicInformation.js
> +    this.handleInputChange = this.handleInputChange.bind(this);
replaced to "onTargetFillToInputChangeHandler" for clarity

2023-10-24 15:27 UTC, Amar-NHS commented on src/app/views/clinic_information/ClinicInformation.js
> +    const {recentInvitationHistory} = this.state;
removed now - good shout. thanks for the tip.

2023-10-24 15:29 UTC, Amar-NHS commented on src/app/views/clinic_information/ClinicInformation.js
> +      console.log("Response status: " + response.status);
had it for testing, now removed.

2023-10-24 15:31 UTC, Amar-NHS commented on src/app/views/clinic_information/ClinicInformation.js
> +      throw error; // Re-throw the error to propagate it.
Its removed.

2023-10-24 15:59 UTC, Amar-NHS commented on src/app/views/clinic_information/clinic_invitation_criteria/ClinicInvitationCriteria.jsx
> +            data-testid="input-target-percentage"
thanks it was used for testing but now removed.

2023-10-24 16:00 UTC, Amar-NHS commented on src/app/views/clinic_information/clinic_invitation_criteria/ClinicInvitationCriteria.jsx
> +            name="weight"
had pulled the element from existing codebase, now removed.

2023-10-24 16:03 UTC, Amar-NHS commented on src/app/views/clinic_information/clinic_invitation_criteria/ClinicInvitationCriteria.jsx
> +      <br />
removed.

2023-10-24 16:04 UTC, Amar-NHS commented on src/app/views/clinic_information/clinic_invitation_criteria/ClinicInvitationCriteria.jsx
> +  // const { appsRemaining } =
removed

2023-10-24 16:05 UTC, Amar-NHS commented on src/app/views/clinic_information/ClinicInformation.js
> +        console.log(targetPercentageValue);
thanks, now removed

2023-10-24 16:05 UTC, Amar-NHS commented on src/app/views/clinic_information/ClinicInformation.js
> +        console.log(response);
removed

2023-10-24 16:21 UTC, Amar-NHS commented on src/app/views/clinic_information/ClinicInformation.js
> +      "isInputTargetPercentageExceed" : true,
As discussed, we changed the variable name and had the initial state to false.

2023-10-24 16:22 UTC, Amar-NHS commented on src/app/views/clinic_information/ClinicInformation.js
> +      return response.data; // You might want to return the response data too.
removed

2023-10-24 16:23 UTC, Amar-NHS commented on src/app/views/clinic_information/ClinicInformation.js
> +    if (!value) {
repurposed the if statement to accommodate the state variable name change

2023-10-25 10:24 UTC, msandhuNHS approved these changes

2023-10-25 11:32 UTC, Amar-NHS commented on src/app/views/clinic_information/clinic_invitation_criteria/ClinicInvitationCriteria.jsx
> +      <h2 label="header">Clinic Invitation Criteria</h2>
Added id fields

2023-10-25 11:32 UTC, Amar-NHS commented on src/app/views/clinic_information/clinic_invitation_criteria/ClinicInvitationCriteria.jsx
Added id fields to the elements

2023-10-25 11:56 UTC, zainm97 commented on src/app/views/clinic_information/ClinicInformation.js
> +  onTargetFillToInputChangeHandler(e) {
Don't action: put this with other handlers

2023-10-25 14:18 UTC, zainm97 commented on src/app/views/clinic_information/ClinicInformation.js
> +      hideUserErrorTargetPercentageExceed,
still reading as hide user error. Minor change probably not worth actioning but tad confusing

2023-10-25 14:19 UTC, zainm97 commented on src/app/views/clinic_information/ClinicInformationPage.jsx
> +            props={recentInvitationHistory}
looks odd to name a prop "props". Can see it was done above but wanna pass that through as recentInvitationHistory

2023-10-25 14:22 UTC, zainm97 requested changes
one real  quick change to remove recentInvitationHistory from ClinicInvitationCriteria component instantiation but looks good otherwise

2023-10-25 14:32 UTC, msandhuNHS approved these changes

2023-10-25 15:03 UTC, zainm97 commented on src/app/views/clinic_information/ClinicInformation.js
> +  calculateTargetAppsToFill(targetFillToInputValue) {
Thinks there some duplication of functions

2023-10-25 15:04 UTC, zainm97 requested changes
remove duplicate code pls

2023-10-25 15:25 UTC, zainm97 approved these changes
Fellas good work. Tested front end and works well. Good work

2023-10-25 15:34 UTC, msandhuNHS submitted a review, later dismissed

2023-10-30 14:21 UTC, zainm97 commented on src/app/views/clinic_information/ClinicInformation.js
> +          console.log(response);
can remove log

2023-10-30 14:22 UTC, zainm97 commented on src/app/views/clinic_information/ClinicInformation.js
> +            // cancelChangeText: "Change clinic",
duplicate with below

2023-10-30 14:30 UTC, zainm97 commented on src/app/views/clinic_information/ClinicInformation.js
> +            // displayClinicSelector: false
if we dont need to set the commented out values lets remove them

2023-10-30 14:30 UTC, zainm97 requested changes
some small fixes required

2023-10-31 10:46 UTC, zainm97 approved these changes
NOICE

2023-10-31 12:41 UTC, msandhuNHS approved these changes

2023-11-01 12:57 UTC, zainm97 submitted a review, later dismissed

2023-11-06 12:07 UTC, zainm97 commented on src/app/views/clinic_information/ClinicInformation.js
> +import ClinicInformationPage from "./ClinicInformationPage";
use single quotes

2023-11-06 13:32 UTC, zainm97 commented on src/app/views/clinic_information/ClinicInformation.js
> +          }, () => {
whats going on here?

2023-11-06 13:34 UTC, zainm97 commented on src/app/views/clinic_information/ClinicInformation.js
> +                // This callback will execute after the state has been updated
theres a method that i've pulled into my changes called componentDidUpdate which compares the previous state with the current state. Think it would be a good idea to move this into there however we can do that in a ticket further down the line to refactor

2023-11-06 13:36 UTC, zainm97 commented on src/app/views/clinic_information/WeeklyCapacityTable.jsx
> +                <br />
screen reader will have issues reading the br from what Collin demoed to us. Can you use a \n in the sprint instead?

2023-11-06 13:37 UTC, zainm97 submitted a review, later dismissed

2023-11-10 12:54 UTC, zainm97 approved these changes

2023-11-10 12:56 UTC, Abdul-NHS approved these changes

2023-11-10 12:57 UTC, merged