Gal 471/sort preinvite data
NHSDigital/Galleri-Frontend pull request #37
Opened 2023-10-31 13:21 UTC by Abdul-NHS

clinics listed in the 'Clinic List' section are now ordered from oldest to newest invitation sent date as per Figma screens

Bug: https://nhsd-jira.digital.nhs.uk/browse/GAL-471

- [ ] Refactoring (non-breaking change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
- [ ] I have followed the code style of the project
- [ ] I have added tests to cover my changes
- [ ] I have updated the documentation accordingly
- [ ] This PR is a result of pair or mob programming

---

## Sensitive Information Declaration

To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this matter.

- [ ] I confirm that neither PII/PID nor sensitive data are included in this PR and the codebase changes.

2023-11-01 12:57 UTC, zainm97 requested changes
just need to turn off prettier till we have a dev session to align on the whitespace and indents and stuff. Code looks all good though!

2023-11-01 15:29 UTC, Amar-NHS reviewed
Code looks good. Can't run and check at the moment because of the Backend not stable

2023-11-06 12:06 UTC, zainm97 approved these changes

2023-11-08 14:35 UTC, Amar-NHS approved these changes

2023-11-14 17:20 UTC, merged