Gal 184/deploy UI build pipeline
NHSDigital/Galleri-Frontend pull request #4
Opened 2023-07-14 12:48 UTC by msandhuNHS

Changes:

1. deploy yaml role assume, bucket name and region set as vars

2023-07-14 13:04 UTC, zainm97 requested changes

2023-07-14 13:04 UTC, zainm97 commented on .gitignore
> +/gpush.sh
can we take this out and put it in on a separate PR. Its not related to the ticket

2023-07-14 13:04 UTC, zainm97 commented on Makefile
> +# asdf-install \
can we add this to the separate PR mentioned in above comment

2023-07-14 13:04 UTC, zainm97 commented on README.md
> +Make use of this repository template to expedite your project setup and enhance your productivity right from the get-go. Enjoy the advantage of having a well-structured, self-documented project that
remove

2023-07-14 13:04 UTC, zainm97 commented on gfeature.sh
> +git checkout -b "gal-$1/$2" develop
changes to be put in separate PR

2023-07-14 13:04 UTC, zainm97 commented on gpush.sh
> +git add .
changes to be put in separate PR

2023-07-14 13:04 UTC, zainm97 commented on package.json
> +    "asdf": "^1.2.2",
is asdf a depandacy we need to commit to the project? We needed to do a global install for the commit hooks but not sure we should be adding to the repo

2023-07-14 13:05 UTC, msandhuNHS commented on .gitignore
> +/gpush.sh
Sounds good, will remove these bash files

2023-07-14 13:11 UTC, zainm97 requested changes

2023-07-14 13:11 UTC, zainm97 commented on .github/workflows/deploy-to-s3.yaml
> +          aws s3 sync ./out s3://${{ vars.BUCKET_NAME }}/
i cant see any local directory that is ./out in your branch. The files that already exist in the bucket looks like they come from different locations within your local repo

2023-07-14 13:34 UTC, msandhuNHS commented on .github/workflows/deploy-to-s3.yaml
> +          aws s3 sync ./out s3://${{ vars.BUCKET_NAME }}/
nextjs puts production files in .out/ directory and is generated at build

2023-07-18 10:14 UTC, zainm97 approved these changes
Looks good sir

2023-07-18 10:18 UTC, LaithM96 requested changes
Looks all good and checks all passed, can you please update your code with the comments in each code :)

2023-07-18 10:21 UTC, merged