Gal 606/render clinic fill target and radius
NHSDigital/Galleri-Frontend pull request #54
Opened 2023-11-16 16:42 UTC by msandhuNHS

## Description

Updated frontend to fetch clinic data values from db.

1. Rendering fillToTargetPercentage
2. Rendering lastSelectedRange
3. Removed console logs
4. Refactoring clinic information component code

## Context

## Type of changes

- [ ] Refactoring (non-breaking change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
- [ ] I have followed the code style of the project
- [ ] I have added tests to cover my changes
- [ ] I have updated the documentation accordingly
- [ ] This PR is a result of pair or mob programming

---

## Sensitive Information Declaration

To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this matter.

- [ ] I confirm that neither PII/PID nor sensitive data are included in this PR and the codebase changes.

2023-11-16 16:52 UTC, zainm97 commented on src/app/views/clinic_information/ClinicInformation.js
> +        console.log(initialSelectedClinic);
left in log

2023-11-16 16:53 UTC, zainm97 commented on src/app/components/pagination.js
> +    // console.log('prev');
this looks incomplete

2023-11-16 16:53 UTC, zainm97 commented on src/app/components/pagination.js
> +    // console.log('next');
this looks incomplete

2023-11-16 16:53 UTC, zainm97 commented on gulpfile.js
> +      // console.log(err)
do you need to comment this back in? Need to use console.error then wont need process.exit(1) below

2023-11-16 16:55 UTC, zainm97 commented on src/app/views/clinic_information/ClinicInformation.js
> +            const lastSelectedRange = response.data.LastSelectedRange.N;
theres a lot of duplicated code. Seems like a good opportunity to store code in single place and call it here

2023-11-16 16:59 UTC, zainm97 commented on src/app/views/clinic_information/ClinicInformation.js
You haven't pulled on to main. You need to update the correct axios calls to pass through these values. And then update the "miles" in the axios call to the get-lsoa-in-range to pass through this value on default

2023-11-16 16:59 UTC, zainm97 commented on src/app/views/invitation_planning/InvitationPlanning.js
> +
?

2023-11-16 17:01 UTC, zainm97 requested changes
Please address changes

2023-11-16 17:33 UTC, msandhuNHS commented on src/app/views/clinic_information/ClinicInformation.js
That may be another tickets work? I pulled from main.

2023-11-16 17:33 UTC, msandhuNHS commented on gulpfile.js
> +      // console.log(err)
Will leave commented out, doesn't effect anything.

2023-11-17 11:15 UTC, zainm97 commented on gulpfile.js
> +      // console.log(err)
common dev processes and standards need to be followed. Please address

2023-11-17 11:16 UTC, zainm97 commented on src/app/components/pagination.js
> +    // console.log('prev');
Please can you address the comment

2023-11-17 11:17 UTC, zainm97 commented on src/app/components/pagination.js
> +    // console.log('next');
Please can you address the comment

2023-11-17 11:21 UTC, zainm97 commented on src/app/views/clinic_information/ClinicInformation.js
> +            const lastSelectedRange = response.data.LastSelectedRange.N;
Please can you address the comment before closing it out

2023-11-17 11:22 UTC, zainm97 commented on src/app/views/invitation_planning/InvitationPlanning.js
> +
Please may you handle the response. Seems best practice to put something in even if its just a log

2023-11-17 11:22 UTC, zainm97 commented on src/app/views/invitation_planning/InvitationPlanning.js
> +
Please may you handle the response. Seems best practice to put something in even if its just a log

2023-11-17 11:23 UTC, zainm97 requested changes
Hi Manny, none of my comments were address - they were just marked as closed with no comments back. Please can you address the conversation at least

2023-11-17 11:54 UTC, msandhuNHS commented on src/app/components/pagination.js
> +    // console.log('prev');
This is for debugging purposes, am commenting out so main does not have logs

2023-11-17 11:56 UTC, msandhuNHS commented on src/app/views/clinic_information/ClinicInformation.js
> +            const lastSelectedRange = response.data.LastSelectedRange.N;
Have just added two fields. As per Cheng's comment, we need to get it functioning, it's perfectly fine to treat it this way for now. Code cleanup if necessary can occur later. I am happy with this code.

2023-11-17 11:57 UTC, msandhuNHS commented on src/app/views/invitation_planning/InvitationPlanning.js
> +
Errors should never log to browser unless for debugging in dev phase. This is fine to comment out. Again all logs are commented out for main. They can be enabled during development.

2023-11-17 11:57 UTC, msandhuNHS commented on src/app/views/invitation_planning/InvitationPlanning.js
> +
same as before.

2023-11-17 12:00 UTC, msandhuNHS commented on gulpfile.js
> +      // console.log(err)
Yes, going into main, leave commented out, only needed for debug purposes.

2023-11-17 12:51 UTC, msandhuNHS commented on gulpfile.js
> +      // console.log(err)
Have now commented back in.

2023-11-17 12:52 UTC, msandhuNHS commented on src/app/components/pagination.js
> +    // console.log('prev');
Have now deleted these logs as per Cheng's request.

2023-11-17 12:52 UTC, msandhuNHS commented on src/app/components/pagination.js
> +    // console.log('next');
Deleted as above.

2023-11-17 12:54 UTC, msandhuNHS commented on src/app/views/clinic_information/ClinicInformation.js
> +            const lastSelectedRange = response.data.LastSelectedRange.N;
Other than directly unpacking the request response into setState() I am unsure how to clean this up. I'd prefer having consts hold the response data.

2023-11-21 09:19 UTC, zainm97 commented on src/app/views/clinic_information/ClinicInformation.js
> +              // () => {
why is this commented out? it should be removed or put in a helper file if we are going to use it in the future. Or at the very least it should have a comment explaining why it is commented out

2023-11-21 09:20 UTC, zainm97 commented on src/app/views/clinic_information/LsoaTable.jsx
> +          name="miles"milesOptions
odd, what is this doing

2023-11-21 10:04 UTC, msandhuNHS commented on src/app/views/clinic_information/LsoaTable.jsx
> +          name="miles"milesOptions
Typo have removed. Didn't break functionality.

2023-11-21 14:02 UTC, msandhuNHS commented on src/app/views/clinic_information/ClinicInformation.js
> +              // () => {
I'm not too sure how this fits into the functionality as it was implemented from a different ticket. Commented out incase someone else needed it. Thought it self explanatory so didn't add a comment. I can delete it as I don't think it's needed, certainly doesn't break new functionality.

2023-11-21 15:48 UTC, zainm97 commented on src/app/views/clinic_information/ClinicInformation.js
> +              // () => {
I think i was trying to say that this functionality will be used later in the calculate number to invite button so it is ok to leave in but a small comment describing the above will be helpful to whoever picks up the ticket

2023-11-22 17:51 UTC, closed without merging