Gal-414 & Gal-315 - Calculate number to invite
NHSDigital/Galleri-Frontend pull request #56
Opened 2023-11-22 11:56 UTC by Abdul-NHS

https://nhsd-jira.digital.nhs.uk/browse/GAL-414

## Type of changes

- [ ] Refactoring (non-breaking change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
- [ ] I have followed the code style of the project
- [ ] I have added tests to cover my changes
- [ ] I have updated the documentation accordingly
- [ ] This PR is a result of pair or mob programming

---

## Sensitive Information Declaration

To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this matter.

- [ ] I confirm that neither PII/PID nor sensitive data are included in this PR and the codebase changes.

2023-11-23 11:25 UTC, msandhuNHS requested changes

2023-11-23 11:25 UTC, msandhuNHS commented on src/app/components/pagination.js
> +                        /*class= {`style_current__K8c2u ${currentPage == pgNumber ? 'active' : ''} `} */
do we want to delete these comments?

2023-11-23 11:26 UTC, Abdul-NHS commented on src/app/components/pagination.js
> +                        /*class= {`style_current__K8c2u ${currentPage == pgNumber ? 'active' : ''} `} */
Hi Manny, left this in for the next pagination tickets, however will remove

2023-11-23 11:29 UTC, msandhuNHS approved these changes

2023-11-29 10:29 UTC, andrew-cleveland approved these changes

2023-11-29 13:47 UTC, zainm97 submitted a review, later dismissed

2023-11-29 14:06 UTC, Amar-NHS submitted a review, later dismissed
As discussed over, let's address those comments in next clean up ticket.

2023-11-29 14:09 UTC, zainm97 commented on src/app/views/clinic_information/ClinicInformation.js
> +    })
will do in general refactor

2023-11-29 14:09 UTC, zainm97 commented on src/app/views/clinic_information/ClinicInformation.js
>    }
will do in general refactor

2023-11-29 14:09 UTC, zainm97 commented on src/app/views/clinic_information/ClinicInformation.js
>            })
will do in general refactor

2023-11-29 14:09 UTC, zainm97 commented on src/app/views/clinic_information/ClinicInformation.js
>                    });
will do in general refactor

2023-11-29 14:09 UTC, zainm97 commented on src/app/views/clinic_information/LsoaTable.jsx
> +import { AppStateContext } from '@/app/context/AppStateContext';
good spot

2023-11-29 14:10 UTC, zainm97 commented on src/app/views/clinic_information/LsoaTable.jsx
> +import { AppStateContext } from '@/app/context/AppStateContext';
sorr this has been actioned and is not there anymore

2023-11-29 14:11 UTC, zainm97 commented on src/app/views/clinic_information/ClinicInformation.js
> +
done

2023-11-29 14:19 UTC, zainm97 approved these changes

2023-11-29 14:19 UTC, Amar-NHS approved these changes
Approved.

2023-11-29 14:20 UTC, merged