AC - added URL references
NHSDigital/Galleri-Frontend pull request #63
Opened 2023-11-30 12:16 UTC by andrew-cleveland

## Description
Added URL environment variables for API ID

## Context
As the API ID will change every time the api gateway is re-deployed this should stop the manual change currently needed.

## Type of changes

- [x] Refactoring (non-breaking change)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
- [x] I have followed the code style of the project
- [ ] I have added tests to cover my changes
- [ ] I have updated the documentation accordingly
- [ ] This PR is a result of pair or mob programming

---

## Sensitive Information Declaration

To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this matter.

- [x] I confirm that neither PII/PID nor sensitive data are included in this PR and the codebase changes.

2023-11-30 13:05 UTC, Abdul-NHS submitted a review, later dismissed

2023-11-30 14:02 UTC, zainm97 requested changes
the code looks good, its just the linter you’re using has changed a lot of double quote to single quotes and in the state variables removed them. It doesn't impact functionality but make review a lot harder i.e when someone else pushes up code they will have a different config. 

Until agree on a linter we have just disabled it on our ends. Would you be able to revert the changes back so that its in line with the current conventions. Know its a pain sorry :(

2023-11-30 15:01 UTC, Abdul-NHS approved these changes

2023-11-30 15:14 UTC, zainm97 submitted a review, later dismissed
Thanks, looks good

2023-12-01 10:26 UTC, Abdul-NHS approved these changes

2023-12-01 10:30 UTC, umayrsNHS approved these changes
LGTM

2023-12-01 10:32 UTC, merged